version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: ./.eslintrc.json
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
  git-legal:
    enabled: true
